-- Snowflake Database Setup Script
-- This script creates the necessary tables for the healthcare app

-- Create USERS table
CREATE TABLE IF NOT EXISTS USERS (
  USER_ID VARCHAR PRIMARY KEY,
  USERNAME VARCHAR NOT NULL UNIQUE,
  PASSWORD_HASH VARCHAR NOT NULL,
  EMAIL VARCHAR NOT NULL UNIQUE,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Create PHYSICIANS table
CREATE TABLE IF NOT EXISTS PHYSICIANS (
  PHYSICIAN_ID VARCHAR PRIMARY KEY,
  NAME VARCHAR NOT NULL,
  SPECIALTY VARCHAR,
  PRACTICE VARCHAR,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Create USER_PHYSICIAN_ASSIGNMENT table
CREATE TABLE IF NOT EXISTS USER_PHYSICIAN_ASSIGNMENT (
  ASSIGNMENT_ID VARCHAR PRIMARY KEY,
  USER_ID VARCHAR NOT NULL,
  PHYSICIAN_ID VARCHAR NOT NULL,
  SALES_GEOGRAPHY VARCHAR NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
  FOREIGN KEY (PHYSICIAN_ID) REFERENCES PHYSICIANS(PHYSICIAN_ID),
  UNIQUE (USER_ID, PHYSICIAN_ID)
);

-- Create CONVERSATION_HISTORY table for message tracking
CREATE TABLE IF NOT EXISTS CONVERSATION_HISTORY (
  CONVERSATION_ID VARCHAR PRIMARY KEY,
  USER_ID VARCHAR NOT NULL,
  PHYSICIAN_ID VARCHAR NOT NULL,
  MESSAGE_ROLE VARCHAR NOT NULL,
  MESSAGE_CONTENT VARCHAR NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
  FOREIGN KEY (PHYSICIAN_ID) REFERENCES PHYSICIANS(PHYSICIAN_ID)
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS IDX_USER_PHYSICIAN ON USER_PHYSICIAN_ASSIGNMENT(USER_ID);
CREATE INDEX IF NOT EXISTS IDX_CONVERSATION_USER ON CONVERSATION_HISTORY(USER_ID);
CREATE INDEX IF NOT EXISTS IDX_CONVERSATION_PHYSICIAN ON CONVERSATION_HISTORY(PHYSICIAN_ID);

-- Insert sample data
INSERT INTO USERS (USER_ID, USERNAME, PASSWORD_HASH, EMAIL)
VALUES 
  ('user_001', 'john_rep', '$2b$10$example_hash_1', 'john@salesrep.com'),
  ('user_002', 'sarah_rep', '$2b$10$example_hash_2', 'sarah@salesrep.com')
ON CONFLICT DO NOTHING;

INSERT INTO PHYSICIANS (PHYSICIAN_ID, NAME, SPECIALTY, PRACTICE)
VALUES 
  ('phys_001', 'Dr. James Smith', 'Cardiology', 'Heart Health Clinic'),
  ('phys_002', 'Dr. Maria Garcia', 'Internal Medicine', 'City Medical Center'),
  ('phys_003', 'Dr. Robert Johnson', 'Cardiology', 'Premier Heart Institute'),
  ('phys_004', 'Dr. Linda Chen', 'Pediatrics', 'Children\'s Hospital')
ON CONFLICT DO NOTHING;

INSERT INTO USER_PHYSICIAN_ASSIGNMENT (ASSIGNMENT_ID, USER_ID, PHYSICIAN_ID, SALES_GEOGRAPHY)
VALUES 
  ('assign_001', 'user_001', 'phys_001', 'Northeast'),
  ('assign_002', 'user_001', 'phys_002', 'Northeast'),
  ('assign_003', 'user_002', 'phys_003', 'Southeast'),
  ('assign_004', 'user_002', 'phys_004', 'Southeast')
ON CONFLICT DO NOTHING;
